### ISSUE TITLE
How to convert .bib into website page using hugo

### ISSUE THREAD

**Issue by njtierney** [R-miss-tastic/website#1]
To avoid writing up summaries of all missing data articles, we should be able to take a .bib file and convert it to a HTML page. This could then manage the articles and keywords etc.

Here are [Some resources for converting .bib into Hugo](https://discourse.gohugo.io/t/how-can-i-manage-a-publication-list-in-hugo-preferrably-from-bibtex-file/2089/4) to get started

**Comment by njtierney** [comment]
Some other resources:

- [bib2html](https://www.lri.fr/~filliatr/bibtex2html/)
- [discussion on importing .bib publication list](https://github.com/gcushen/hugo-academic/issues/146)
- [python script](https://gist.github.com/andrewfowlie/4e556851384c35f2031b080341f70d19#file-hugo_academic_from_arxiv-py)
- [bibtex parser for Go](https://github.com/nickng/bibtex)

- [this blog post -Automatically importing publications from bibtex to a hugo-academic blog](https://lbusettspatialr.blogspot.com/2018/03/automatically-importing-publications.html) sounds pretty good!

- There's also a .bib parser for R, that converts .bib files into a tibble - [bib2df](https://github.com/ropensci/bib2df). I wonder if that could be used to help create a lookup table as well

So I think that, worst case, we should be able to write something that wraps `bib2df` and does some HTML munging. Maybe that will be a useful package?

**Comment by njtierney** [comment]
- the [bibtex](https://github.com/romainfrancois/bibtex) package written by romain francois also looks good!

**Comment by njtierney** [comment]
Similar questions:

https://tex.stackexchange.com/questions/11516/alternatives-to-bibtex2html

**Comment by imkemayer** [comment]
One working solution is to build the entire website locally on R Studio (`blogdown::build_site()`) and to push the resulting `.html` files (_bibliography.html_ and _biblio_complete.html_ in the _content_ folder) to GitHub.
