### ISSUE TITLE
How to fix the posts folder to be "posts" instead of the largest subfolder in content?

### ISSUE THREAD

**Issue by imkemayer** [R-miss-tastic/website#16]
It looks like the posts on the home page are taken from the subfolder in "/content/" having the most entries. Since we currently have two subfolders ("/content/posts/" and "/content/packages/") the posts are generated from the larger "packages" subfolder unless there are more entries in "posts".

Temporary fix: add many duplicated posts in "posts" subfolder. Is there a workaround for this or an option to pin certain posts to the top?

**Comment by SteffenMoritz** [comment]
Hey, I think your workaround (of just writing some articles) might be the best solution.


I read there is the 
PaginatePath = "/posts" option, which you could set in the config.toml
Like you set paginate = 3 (to just show 3 posts per page)
You might want to try this.

But it did not work for me . PaginatePath seems not to be supported by our selected theme. Guess we would have to adapt some things at the theme files.

Probably just writing some posts is easier :)

**Comment by TwsThomas** [comment]
Resolved thanks to PR #18
