### ISSUE TITLE
fit the navigation bar items into a single row or completely change the navigation bar layout

### ISSUE THREAD

**Issue by imkemayer** [R-miss-tastic/website#33]
On a 13.3" display, the navigation bar doesn't fit into 1 row (the last item is placed in a second row). It would look nicer and help orientation if everything was on the same row.

Would it take a lot of recoding to change the default navigation bar?

**Comment by tuxette** [comment]
first choice: dropdown menu
second choice: makes a button appear instead of the menu

**Comment by tuxette** [comment]
not implemented in this theme
